# Generated by Django 5.0.2 on 2024-03-02 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=100)),
                ('nome_social', models.CharField(max_length=50)),
                ('profissao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('contato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.CharField(max_length=50)),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profissional')),
            ],
        ),
    ]
