# Generated by Django 5.0.2 on 2024-03-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='id_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_prof', to='api.profissional'),
        ),
    ]
